name: Static Type Check (Checkstyle)[Linting]

on:                                         # Called from the ci.yml
  workflow_call:                            # Allows file to be triggered from another workflow
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      java-version:
        description: 'Java version'
        type: string
        required: true
      gradle-version:
        description: 'Gradle version'
        type: string
        required: true

  workflow_dispatch:                        # Allows file to be triggered manually from the repository
    inputs:
      os:
        description: 'OS'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        required: false
        default: 'ubuntu-latest'
      java-version:
        description: 'Java version'
        type: choice
        options:
          - '17'
        required: false
        default: '17'
      gradle-version:
        description: 'Gradle version'
        type: choice
        options:
          - '7.6'
          - '7.6.1'
        required: false
        default: '7.6'

jobs:
  checkstyle:
    runs-on: ${{ inputs.os }}
    env:
      # on MAC OS, we need to set this environment variable
      # to fix problems with the fork() calls (see this thread
      # for more information: http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html)
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3                         # Checkout is required for local action
      - name: Configure Java and Gradle Version           # Apply a human-readable name
        id: config-java-gradle                            # Apply easy to reference id
        uses: ./.github/workflows/actions/setup-env       # Path reference to local action
        with:                                             # Pass in versions for testing
          gradle-version: ${{ inputs.gradle-version }}
          os: ${{ inputs.os }}

      - name: Checkstyle                                  # Run static type check (Lint)
        run: ./gradlew checkstyleMain

      - name: Archive unit test report                    # Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Checkstyle report
          path: build/reports/checkstyle