name: Full CI Build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "develop"]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-setup-gradle-environment:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/setup-gradle-environment.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

  ubuntu-unit-test-gradle-environment:
    needs: ubuntu-setup-gradle-environment
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/unit-test.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

  ubuntu-int-test-gradle-environment:
    needs: ubuntu-setup-gradle-environment
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/int-test.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

  ubuntu-checkstyle-gradle-environment:
    needs: ubuntu-setup-gradle-environment
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/checkstyle.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

  ubuntu-pmd-gradle-environment:
    needs: ubuntu-setup-gradle-environment
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/pmd.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

  windows-setup-gradle-environment:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ windows-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/setup-gradle-environment.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

#  windows-unit-test-gradle-environment:
#    needs: windows-setup-gradle-environment
#    strategy:
#      matrix:
#        os: [ windows-latest ]
#        gradle-version: [ "7.6", "7.6.1" ]
#      fail-fast: false
#    uses: benrhine/common-json-utils-jackson/.github/workflows/unit-test.yml@main
#    with:
#      os: ${{ matrix.os }}
#      gradle-version: ${{ matrix.gradle-version }}
#
#  windows-int-test-gradle-environment:
#    needs: windows-setup-gradle-environment
#    strategy:
#      matrix:
#        os: [ windows-latest ]
#        gradle-version: [ "7.6", "7.6.1" ]
#      fail-fast: false
#    uses: benrhine/common-json-utils-jackson/.github/workflows/int-test.yml@main
#    with:
#      os: ${{ matrix.os }}
#      gradle-version: ${{ matrix.gradle-version }}

  macos-setup-gradle-environment:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ macos-latest ]
        gradle-version: [ "7.6", "7.6.1" ]
      fail-fast: false
    uses: benrhine/common-json-utils-jackson/.github/workflows/setup-gradle-environment.yml@main
    with:
      os: ${{ matrix.os }}
      gradle-version: ${{ matrix.gradle-version }}

#  macos-unit-test-gradle-environment:
#    needs: macos-setup-gradle-environment
#    strategy:
#      matrix:
#        os: [ macos-latest ]
#        gradle-version: [ "7.6", "7.6.1" ]
#      fail-fast: false
#    uses: benrhine/common-json-utils-jackson/.github/workflows/unit-test.yml@main
#    with:
#      os: ${{ matrix.os }}
#      gradle-version: ${{ matrix.gradle-version }}
#
#  macos-int-test-gradle-environment:
#    needs: macos-setup-gradle-environment
#    strategy:
#      matrix:
#        os: [ macos-latest ]
#        gradle-version: [ "7.6", "7.6.1" ]
#      fail-fast: false
#    uses: benrhine/common-json-utils-jackson/.github/workflows/int-test.yml@main
#    with:
#      os: ${{ matrix.os }}
#      gradle-version: ${{ matrix.gradle-version }}
