name: Setup the Gradle Environment

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      gradle-version:
        description: 'Gradle version'
        type: string
        required: true

jobs:
  environment-setup:
    name: Environment Setup
    id: environment-setup
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Configure Java and Gradle Version
        id: config-java-gradle
        uses: ./.github/workflows/actions/setup_env
        with:
          gradle-version: ${{ inputs.gradle-version }}
          os: ${{ inputs.os }}