name: Setup the Gradle Environment

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      gradle-version:
        description: 'Gradle version'
        type: string
        required: true

jobs:
  setup:
    name: setup
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/workflows/actions/setup-gradle-env.yml
        with:
          os: ${{ inputs.os }}
          gradle-version: ${{ inputs.gradle-version }}