name: Setup the Gradle Environment

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      gradle-version:
        description: 'Gradle version'
        type: string
        required: true

jobs:
  setup:
    name: setup
    runs-on: ${{ inputs.os }}

    steps:
      uses: ./.github/workflows/setup-gradle-env.yml
      with:
        os: ${{ inputs.os }}
        gradle-version: ${{ inputs.gradle-version }}